name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # <– ESSENCIAL para o GitHub Token ter permissão de push
  contents: read
  pages: write
  id-token: write


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verificar se index.html existe
        run: |
          if [ ! -f public/index.html ]; then
            echo "index.html não encontrado!"
            exit 1
          fi

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

